### ISSUE TITLE
Bug Report | I can't interact with the block and the changer tool

### ISSUE THREAD

**Issue by Alpha-1-mtf** [Hirxs-Workshop/FBND.Bedrock-dev#189]
## Necessary information
- **MC Version type:** Bedrock
- **MC version:** The last(1.21)
- **FB&D version:** The last too
- **Discord nametag:** SCP(Renard)

## Bug report desc:
If I take the old pc, i can't interact with him and is the same with the changer tool, and I see that in the party, and i don't understand because i activate all the mod that he need.
![Screenshot_2024-11-24-13-38-44-58_5c8300b655012b1930f2e0a7b81bf6a9](https://github.com/user-attachments/assets/73e9801a-b5a3-4b08-8ddc-b42b69af9c43)

**Comment by Hirxs-MC** [comment]
Greetings, it seems that you have an old version of the add-on, download the new version here https://github.com/Hirxs-Workshop/FBND.Bedrock-dev/releases/tag/official-release-v4.9
