### ISSUE TITLE
Door bug

### ISSUE THREAD

**Issue by Zero001two** [Hirxs-Workshop/FBND.Bedrock-dev#192]
For some reason all the addon doors are bugged just for me, so there is a picture of what is happening and just one picture but what is in it and what happened to 
all of them.

(https://github.com/user-attachments/assets/d2625107-1367-4f9f-b53f-0a3d68fcaf68)

**Comment by Zero001two** [comment]
:3

**Comment by Hirxs-MC** [comment]
I hope this helps

> ## FAQ for the recent update:
> ### Why does the item changer tool not change variants and some blocks can only be rotated to one position?
> - Check if you have the new update activated in your world, it is under the name `BP/RP | 1.21.50+ | FB&D v4.9.1`
> - Remove any old version of the add-on from your MC from the settings in the storage section
> - Check if you have beta api and upcoming creators features activated
> - Check if you really have version 1.21.50
> 
> ### What do I do if none of the above worked?
> - You can check if you did not confuse both files from the github download since there is one that has `stable_` as the initial word and another `preview_`
>    - For mc official is **stable_FBD-v4-9-1.mcaddon**
>    - For mc preview is **preview_FBD-v4-9-1.mcaddon**
> 
> -# <@&1307457063307186249>

**Comment by Zero001two** [comment]
For some reason I had to create a new map, but it's ok because I didn't do
much on the other map.

Em ter., 10 de dez. de 2024 22:04, Hyrxs ***@***.***>
escreveu:

**Comment by Hirxs-MC** [comment]
Oh, but you were able to fix the problem, right?

**Comment by Zero001two** [comment]
Yes, I did.

Em ter., 10 de dez. de 2024 22:56, Hyrxs ***@***.***>
escreveu:
