### ISSUE TITLE
Bug Report | Changer Tool not Working

### ISSUE THREAD

**Issue by Paintman5001** [Hirxs-Workshop/FBND.Bedrock-dev#193]
## Necessary information
- **MC Version type:** Bedrock
- **MC version:** 1.21.51
- **FB&D version:** Preview 4.9.1
- **Discord nametag:** @AGameEnjoyer

## Bug report desc:
(Write here an explanation/summary or more of your report)
The Changer Tool does not work on the latest version, this makes building and decorating very difficult.

Turns out I'm using the wrong version, my bad

**Comment by Hirxs-MC** [comment]
# I hope this helps

> ## FAQ for the recent update:
> ### Why does the item changer tool not change variants and some blocks can only be rotated to one position?
> - Check if you have the new update activated in your world, it is under the name `BP/RP | 1.21.50+ | FB&D v4.9.1`
> - Remove any old version of the add-on from your MC from the settings in the storage section
> - Check if you have beta api and upcoming creators features activated
> - Check if you really have version 1.21.50
> 
> ### What do I do if none of the above worked?
> - You can check if you did not confuse both files from the github download since there is one that has `stable_` as the initial word and another `preview_`
>    - For mc official is **stable_FBD-v4-9-1.mcaddon**
>    - For mc preview is **preview_FBD-v4-9-1.mcaddon**

**Comment by Paintman5001** [comment]
i figured it out eventually but thanks hirxs!
